services:
  nginx:
    build:
      context: apps
      dockerfile: nginx/Dockerfile
    restart: on-failure
    networks:
      - default
      - proxy
    depends_on:
      php:
        condition: service_started
    labels:
      - stage=${TAG}
      - traefik.enable=true
      - traefik.http.routers.${TAG}-app.rule=Host(`${TAG}.staging.localhost`)
      - traefik.docker.network=proxy

  php:
    build:
      context: apps/php
      target: php
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build:
      context: apps/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: on-failure

networks:
  default: ~
  proxy:
    external: true
