services:
  traefik:
    image: traefik
    networks:
      - proxy
    command:
      - "--api.insecure=true" # Only for demo purposes
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: on-failure

networks:
  proxy:
    external: true
